import { Router } from "express";

const router = Router();

import AuthRoutes from "./auth.routes.js";
import UserRoutes from "./user.routes.js";
import DepartmentRoutes from "./department.routes.js";
import PositionRoutes from "./position.routes.js";
import ScheduleRoutes from "./schedule.routes.js";
import ShiftRoutes from "./shift.routes.js";
import UserShiftRoutes from "./usershift.routes.js";
import DepartmentUsersRoutes from "./departmentusers.routes.js";
import UserPositionRoutes from "./userposition.routes.js";
import TaskListRoutes from "./tasklist.routes.js";
import TaskListItemsRoutes from "./tasklistitems.routes.js";
import UserShiftTaskListRoutes from "./usershifttasklist.routes.js";
import TaskListItemStatusRoutes from "./tasklistitemstatus.routes.js";
import ClockInOutRoutes from "./clockinout.routes.js";
import UnavailableRoutes from "./unavailable.routes.js";
import SwapShiftRequestRoutes from "./swapshiftrequest.routes.js";
import NotificationRoutes from "./notification.routes.js";
import UserNotificationRoutes from "./usernotification.routes.js";
import SettingsRoutes from "./settings.routes.js";
import SettingsValuesRoutes from "./settingsvalues.routes.js";
import CalendarRoutes from "./calendar.routes.js";
import BudgetRoutes from "./budget.routes.js";
import BudgetCostRoutes from "./budgetcost.routes.js";
import AnnouncementRoutes from "./announcements.routes.js";

router.use("/", AuthRoutes);
router.use("/users", UserRoutes);
router.use("/departments", DepartmentRoutes);
router.use("/positions", PositionRoutes);
router.use("/schedules", ScheduleRoutes);
router.use("/shifts", ShiftRoutes);
router.use("/usershifts", UserShiftRoutes);
router.use("/departmentusers", DepartmentUsersRoutes);
router.use("/userpositions", UserPositionRoutes);
router.use("/tasklist", TaskListRoutes);
router.use("/tasklistitems", TaskListItemsRoutes);
router.use("/usershifttasklist", UserShiftTaskListRoutes);
router.use("/tasklistitemstatus", TaskListItemStatusRoutes);
router.use("/clockinout", ClockInOutRoutes);
router.use("/unavailable", UnavailableRoutes);
router.use("/swapshiftrequest", SwapShiftRequestRoutes);
router.use("/notifications", NotificationRoutes);
router.use("/usernotifications", UserNotificationRoutes);
router.use("/settings", SettingsRoutes);
router.use("/settingsvalues", SettingsValuesRoutes);
router.use("/calendar", CalendarRoutes);
router.use("/budgets", BudgetRoutes);
router.use("/budget-costs", BudgetCostRoutes);
router.use("/announcements", AnnouncementRoutes);

export default router;
